### ISSUE TITLE
Memory leak issue with Kristal

### ISSUE THREAD

**Issue by FireRainV** [KristalTeam/Kristal#334]
The more you unload or reload, even the Kristal main menu, when attempting to load a mod, the loading times and memory usage increases on a crazy level. The only temporary fix is to close and reopen Kristal.

**Comment by ghost** [comment]
Are there any updates on this? This is such a critical issue with Kristal currently.

**Comment by ghost** [comment]
@NyakoFox , @SylviBlossom  I actually found the source of the memory leak.
It's the function `Registry.initialize()` that being called at `Kristal.clearModState()`.

I tried commenting it and disabling crashes temporarily. And no leak! mods loaded instantly, no matter how many reloads I did.
I tried to fix it myself, but I couldn't manage, so I leave it to you guys as you know this stuff more than I do.

**Comment by ghost** [comment]
I'm guessing that the Registry isn't being cleared properly before being initialized again.

**Comment by ghost** [comment]
Fixed at https://github.com/KristalTeam/Kristal/pull/453

**Comment by ghost** [comment]
Why did it got reopened? I already fixed the leak.
Is my fix not good?

**Comment by AcousticJamm-dev** [comment]
Nyako mentioned this in the server so it's fair that you don't know, but she doesn't like closing issues for unmerged solutions.

Edit: My mistake. She commented it on one of your issues that you closed yourself.

**Comment by Hyperfae** [comment]
It's reopened because the issue is still present on mainline Kristal (not your fork).

If a pull request fixes an issue, all you have to do is put "Fixes #[issue number]" in the PR description.

**Comment by ghost** [comment]
That's it!
The most bothering issue with Kristal has been applied!
I was glad to be the one who helped fix it.
